# Generated by Django 3.0.8 on 2020-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://image.flatico                              n.com/icons/svg/38/38645.svg', upload_to=''),
        ),
    ]
