# Generated by Django 3.0.8 on 2020-07-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200731_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
    ]
